# Generated by Django 4.1.7 on 2023-03-22 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=100, verbose_name="Cnpj")),
                ("adress", models.CharField(max_length=100, verbose_name="Logradouro")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("country", models.CharField(max_length=100, verbose_name="País")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(max_length=100, verbose_name="Centro de custo"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "integration_code",
                    models.CharField(
                        max_length=100, verbose_name="Código de integração"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentEmployee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO"),
                            ("DEV", "Developer"),
                            ("MANAGER", "Manager"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                ("phone", models.CharField(max_length=100, verbose_name="Telefone")),
                ("birth", models.DateField(verbose_name="Data de nascimento")),
                ("entry", models.DateField(verbose_name="Data de entrada")),
                (
                    "shutdown",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de desligamento"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "departments",
                    models.ManyToManyField(
                        related_name="employees",
                        through="company.DepartmentEmployee",
                        to="company.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departmentemployee",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.employee"
            ),
        ),
    ]
